# Generated by Django 3.0 on 2019-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrow',
            name='height',
            field=models.PositiveIntegerField(choices=[(1, 'Не вырасло'), (2, 'Вырасло')], default=1),
        ),
    ]
